### ISSUE TITLE
Change the frequency of obscure genres

### ISSUE THREAD

**Issue by jazzsequence** [BinaryJazz/genrenator#7]
The genres are broken into "main" and "secondary" to avoid obscure genres coming up more frequently than common ones (everything is obscure when you add in all the prefixes/adjectives/regions/etc). Currently there's a 1/3 chance to get a "secondary" genre. Should we decrease this ratio? It seems like we're still getting a lot of obscure ones. 1 in 4? 1 in 5?

Thoughts? @binarygary @allisonplus

**Comment by allisonplus** [comment]
I'd be up for bumping to 1 in 5 and seeing if that evens it out enough.
